name: Build
on:
  push:
jobs:
  build-project:
    name: Brompton Firmware Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Configure and Build Project
        uses: threeal/cmake-action@main

      - name: List Build Directory
        run: ls -R .

      - name: Run Tests
        run: cd build && ./tests/UtilityTests && cd ..