name: Doxygen Action

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mattnotmitt/doxygen-action@v1.9.5
      - name: Doxygen Action
        with:
          doxyfile-path: "./Doxyfile"
          working-directory: "."
