name: Build
on:
  push:
jobs:
  build-project:
    name: Brompton Firmware Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Configure and Build Project
        uses: threeal/cmake-action@main

      - name: Run Tests
        run: cd build && ctest --output-on-failure
      
      - name: Run Dox
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
          config_file: Doxyfile
      